name: CORELOCKULTRA
options:
  bundleIdPrefix: com.dntweaks
  deploymentTarget:
    iOS: "15.0"
targets:
  CORELOCKULTRA:
    type: application
    platform: iOS
    sources: 
      - path: Sources/CORELOCKULTRA
    settings:
      base:
        CODE_SIGNING_REQUIRED: "YES"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: "YES"
        DEVELOPMENT_TEAM: ""
        PRODUCT_BUNDLE_IDENTIFIER: "com.dntweaks.corelockultra"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
